![title](cover/cover.png)

Hope you will like my work !

Please SUBSCRIBE channel going through this link down below :

https://www.youtube.com/channel/UCfayWGHJ9JvTic8NHxfK09Q


-----------------------

# Array :- Creating, Indexing, Slicing, Datatypes

------

In [1]:
import numpy as np

In [3]:
# scalar array / 0-D array
arr = np.array(10)

In [4]:
print(arr)

10


In [5]:
type(arr)

numpy.ndarray

In [6]:
#1-D array

arr_1 = np.array([1,2,3,4,5])

In [9]:
# return dimensions of an array
arr_1.ndim

1

In [10]:
# 2-D array

arr_2 = np.array([[1,2,3,4,5],[1,2,56,4,4]])

In [11]:
arr_2.ndim

2

In [12]:
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 1,  2, 56,  4,  4]])

In [13]:
#3-D array

arr_3 = np.array([[[1,2,3,4],[3,4,5,6]]])

In [15]:
arr_3.ndim

3

In [16]:
arr_3

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]]])

# Indexing

In [17]:
arr_1

array([1, 2, 3, 4, 5])

In [18]:
arr_1[2]

3

In [21]:
arr_2[1,2]

56

In [20]:
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 1,  2, 56,  4,  4]])

# Slicing

In [22]:
arr_1

array([1, 2, 3, 4, 5])

In [23]:
arr_1[1:4]

array([2, 3, 4])

In [24]:
arr_1[2:]

array([3, 4, 5])

In [25]:
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 1,  2, 56,  4,  4]])

In [26]:
arr_2[0,2:4]

array([3, 4])

In [27]:
arr_3

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]]])

In [32]:
arr_3[0,:,2]

array([3, 5])

# Datatypes

string
number
float
boolean

In [33]:
arr_s = np.array(['string','new'])

In [34]:
arr_s

array(['string', 'new'], dtype='<U6')

In [36]:
arr_n = np.array([1,2,3,4], dtype = 'S')

In [37]:
arr_n

array([b'1', b'2', b'3', b'4'], dtype='|S1')