![](cover/cover.png)

Hope you will like my work !

Please SUBSCRIBE channel going through this link down below :

https://www.youtube.com/channel/UCfayWGHJ9JvTic8NHxfK09Q


----------------

# Numpy :  Copy vs View

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr_c = arr.copy()

In [6]:
arr_c[0] = 23

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr_c

array([23,  2,  3,  4,  5])

# View

In [9]:
arr_v = arr.view()

In [10]:
arr_v

array([1, 2, 3, 4, 5])

In [11]:
arr_v[0] = 43

In [12]:
arr_v

array([43,  2,  3,  4,  5])

In [13]:
arr

array([43,  2,  3,  4,  5])