![](cover/cover.png)

Hope you will like my work !

Please SUBSCRIBE channel going through this link down below :

https://www.youtube.com/channel/UCfayWGHJ9JvTic8NHxfK09Q


--------------------

# Numpy : Shape & Reshape

In [2]:
import numpy as np
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [3]:
arr.shape

(2, 5)

In [4]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

# Reshape

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [18]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
arr_2 = arr.reshape((2,7))

In [13]:
arr_2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [14]:
arr_2.ndim

2

In [19]:
# 1-D to 3-D array
arr.reshape((2,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])