![](cover/cover.png)

Hope you will like my work !

Please SUBSCRIBE channel going through this link down below :

https://www.youtube.com/channel/UCfayWGHJ9JvTic8NHxfK09Q


------------

# Numpy : Search & Sorting

------------

# Search

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8])

In [4]:
np.where(arr == 7)

(array([6]),)

In [6]:
np.where(arr%2 == 0 )

(array([1, 3, 5, 7]),)

# Sorting

In [7]:
arr = np.array([1,4,6,3,4,7,8,53,4])

In [8]:
np.sort(arr)

array([ 1,  3,  4,  4,  4,  6,  7,  8, 53])

In [11]:
arr_2 = np.array([[1,4,6,3,4],[2,4,2,4,6]])

In [12]:
np.sort(arr_2)

array([[1, 3, 4, 4, 6],
       [2, 2, 4, 4, 6]])